version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_notification
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:16
    container_name: postgres_notification
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  producer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer-service
    restart: always
    environment:
      APP_NAME: producer-service
      PORT: 3000
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    ports:
      - '3000:3000'
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer-service
    restart: always
    environment:
      APP_NAME: consumer-service
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications
      TELEGRAM_BOT_TOKEN: 8697063589:AAE-gjSxFrC-C0IiTQfek7mMNUQIIcP_jhU
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

volumes:
  postgres_data:
  rabbitmq_data: